version: '3'

services:
  alice:
    build:
      context: ./alice
    image: alicedocker
    container_name: container1
    ports:
      - '8080:8080'
    depends_on:
      - bob

  bob:
    build:
      context: ./bob
    image: bobdocker
    container_name: container2


